// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaidDaddy.Data;

#nullable disable

namespace RaidDaddy.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220921102636_base")]
    partial class @base
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RaidDaddy.Entities.Raider", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<Guid?>("CurrentTeamId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Subclass")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTeamId");

                    b.ToTable("Raiders");
                });

            modelBuilder.Entity("RaidDaddy.Entities.RaidFireteam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Encounter")
                        .HasColumnType("int");

                    b.Property<int>("Raid")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.ToTable("Fireteams");
                });

            modelBuilder.Entity("RaidDaddy.Entities.Raider", b =>
                {
                    b.HasOne("RaidDaddy.Entities.RaidFireteam", "CurrentTeam")
                        .WithMany("Raiders")
                        .HasForeignKey("CurrentTeamId");

                    b.Navigation("CurrentTeam");
                });

            modelBuilder.Entity("RaidDaddy.Entities.RaidFireteam", b =>
                {
                    b.Navigation("Raiders");
                });
#pragma warning restore 612, 618
        }
    }
}
